import { useMemo } from 'react'
import type { Booking } from '../booking'
import { generateReceiptHTML } from '../booking/BookingReceipt'

interface BookingReceiptViewProps {
  booking: Booking
  onPrint?: () => void
  onClose?: () => void
}

/**
 * Renders a print-friendly HTML receipt inside the app. The receipt body is
 * generated by `generateReceiptHTML` so the same template can be reused for
 * email attachments, the public share page, and in-app printing.
 */
export function BookingReceiptView({ booking, onPrint, onClose }: BookingReceiptViewProps) {
  const html = useMemo(() => generateReceiptHTML(booking), [booking])

  const handlePrint = () => {
    onPrint?.()
    if (typeof window !== 'undefined') window.print()
  }

  return (
    <div style={{ background: '#fff', padding: '1rem', borderRadius: 12, border: '1px solid #e5e7eb' }}>
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem', marginBottom: '1rem' }}>
        <button
          onClick={handlePrint}
          style={{
            padding: '0.45rem 0.9rem',
            borderRadius: 8,
            border: '1px solid #d1d5db',
            background: '#fff',
            cursor: 'pointer',
            fontSize: '0.9rem',
          }}
        >
          Print receipt
        </button>
        {onClose && (
          <button
            onClick={onClose}
            style={{
              padding: '0.45rem 0.9rem',
              borderRadius: 8,
              border: '1px solid #d1d5db',
              background: '#fff',
              cursor: 'pointer',
              fontSize: '0.9rem',
            }}
          >
            Close
          </button>
        )}
      </div>

      <div
        className="receipt-body"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  )
}
