import { Campsite, Review } from './types'

export const CAMPSITES: Campsite[] = [
  {
    id: 1,
    name: 'Pine Ridge Campground',
    location: 'Big Sur',
    state: 'CA',
    lat: 36.2704,
    lng: -121.8081,
    type: 'tent',
    rating: 4.8,
    reviewCount: 124,
    pricePerNight: 35,
    available: true,
    amenities: ['Fire pit', 'Picnic table', 'Restrooms', 'Hiking trails'],
    description: 'Nestled among towering pines with stunning coastal views. Perfect for hikers and nature lovers seeking a classic camping experience.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: true,
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 2,
    name: 'Redwood Valley RV Park',
    location: 'Crescent City',
    state: 'CA',
    lat: 41.7558,
    lng: -124.2026,
    type: 'rv',
    rating: 4.2,
    reviewCount: 89,
    pricePerNight: 55,
    available: true,
    amenities: ['Full hookups', 'Dump station', 'WiFi', 'Laundry', 'Showers'],
    description: 'Full-service RV park surrounded by ancient redwoods. Easy access to Jedediah Smith Redwoods State Park.',
    imageUrl: '',
    maxGuests: 8,
    petFriendly: true,
    checkIn: '1:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 3,
    name: 'Lake Tahoe Cabins',
    location: 'South Lake Tahoe',
    state: 'CA',
    lat: 38.9332,
    lng: -119.9843,
    type: 'cabin',
    rating: 4.9,
    reviewCount: 203,
    pricePerNight: 189,
    available: false,
    amenities: ['Kitchen', 'Heating', 'WiFi', 'Hot tub', 'Lake access', 'Ski storage'],
    description: 'Cozy lakeside cabins with panoramic views of Lake Tahoe. Year-round destination for skiing, hiking, and water sports.',
    imageUrl: '',
    maxGuests: 4,
    petFriendly: false,
    checkIn: '4:00 PM',
    checkOut: '10:00 AM',
  },
  {
    id: 4,
    name: 'Joshua Tree Base Camp',
    location: 'Joshua Tree',
    state: 'CA',
    lat: 34.1347,
    lng: -116.3131,
    type: 'tent',
    rating: 4.5,
    reviewCount: 156,
    pricePerNight: 25,
    available: true,
    amenities: ['Fire pit', 'Stargazing', 'Picnic table', 'Vault toilet'],
    description: 'Primitive camping under desert skies. Incredible stargazing and easy access to Joshua Tree National Park climbing routes.',
    imageUrl: '',
    maxGuests: 4,
    petFriendly: false,
    checkIn: '12:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 5,
    name: 'Yosemite Pines',
    location: 'Groveland',
    state: 'CA',
    lat: 37.8651,
    lng: -120.1199,
    type: 'tent',
    rating: 4.7,
    reviewCount: 312,
    pricePerNight: 40,
    available: true,
    amenities: ['Fire pit', 'Bear locker', 'Restrooms', 'Camp store', 'Hiking trails'],
    description: 'Gateway to Yosemite with spacious sites under a canopy of ponderosa pines. Bear-safe food storage provided.',
    imageUrl: '',
    maxGuests: 8,
    petFriendly: true,
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 6,
    name: 'Malibu Creek Cabins',
    location: 'Malibu',
    state: 'CA',
    lat: 34.0259,
    lng: -118.6923,
    type: 'cabin',
    rating: 4.3,
    reviewCount: 67,
    pricePerNight: 145,
    available: true,
    amenities: ['Kitchen', 'A/C', 'Parking', 'Hiking trails', 'Creek access'],
    description: 'Rustic-chic cabins along Malibu Creek. Close to beaches and the Santa Monica Mountains trail system.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: true,
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 7,
    name: 'Mendocino Glamping',
    location: 'Mendocino',
    state: 'CA',
    lat: 39.3077,
    lng: -123.7995,
    type: 'glamping',
    rating: 4.6,
    reviewCount: 45,
    pricePerNight: 175,
    available: true,
    amenities: ['Queen bed', 'Solar power', 'Private bathroom', 'Deck', 'Ocean view'],
    description: 'Luxury safari tents on the Mendocino coast. Fall asleep to the sound of waves with all the comforts of home.',
    imageUrl: '',
    maxGuests: 2,
    petFriendly: false,
    checkIn: '4:00 PM',
    checkOut: '10:00 AM',
  },
  {
    id: 8,
    name: 'Death Valley Outpost',
    location: 'Furnace Creek',
    state: 'CA',
    lat: 36.4573,
    lng: -116.8658,
    type: 'rv',
    rating: 3.9,
    reviewCount: 34,
    pricePerNight: 45,
    available: true,
    amenities: ['Full hookups', 'Pool', 'Dump station', 'Camp store'],
    description: 'The only full-hookup RV park in Death Valley. Oasis in the desert with a spring-fed pool.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: true,
    checkIn: '1:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 9,
    name: 'Sequoia Treehouse',
    location: 'Three Rivers',
    state: 'CA',
    lat: 36.4388,
    lng: -118.7748,
    type: 'glamping',
    rating: 4.9,
    reviewCount: 78,
    pricePerNight: 225,
    available: false,
    amenities: ['Queen bed', 'Composting toilet', 'Solar shower', 'Wraparound deck', 'Breakfast included'],
    description: 'Sleep among the giants in an elevated treehouse near Sequoia National Park. A truly unique glamping experience.',
    imageUrl: '',
    maxGuests: 2,
    petFriendly: false,
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 10,
    name: 'Point Reyes Coastal Camp',
    location: 'Point Reyes Station',
    state: 'CA',
    lat: 38.0699,
    lng: -122.8100,
    type: 'tent',
    rating: 4.4,
    reviewCount: 91,
    pricePerNight: 30,
    available: true,
    amenities: ['Fire pit', 'Vault toilet', 'Picnic table', 'Wildlife viewing'],
    description: 'Hike-in coastal campsite with dramatic cliffs and elk sightings. Permits required — book early for summer.',
    imageUrl: '',
    maxGuests: 4,
    petFriendly: false,
    checkIn: '12:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 11,
    name: 'Mount Shasta Alpine Lodge',
    location: 'Mount Shasta',
    state: 'CA',
    lat: 41.3099,
    lng: -122.3106,
    type: 'cabin',
    rating: 4.6,
    reviewCount: 52,
    pricePerNight: 165,
    available: true,
    amenities: ['Kitchen', 'Fireplace', 'Ski-in access', 'Hot tub', 'WiFi'],
    description: 'Mountain lodge cabins at the base of Mt. Shasta. Ideal for mountaineering, skiing, and hot spring visits.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: true,
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 12,
    name: 'Channel Islands Base Camp',
    location: 'Ventura',
    state: 'CA',
    lat: 34.0069,
    lng: -119.7710,
    type: 'tent',
    rating: 4.8,
    reviewCount: 143,
    pricePerNight: 20,
    available: true,
    amenities: ['Picnic table', 'Wind shelter', 'Vault toilet', 'Snorkeling'],
    description: 'Island camping accessible only by boat. Crystal-clear waters, sea caves, and fox sightings. Bring all your own water.',
    imageUrl: '',
    maxGuests: 4,
    petFriendly: false,
    checkIn: '11:00 AM',
    checkOut: '11:00 AM',
  },
]

export const REVIEWS: Review[] = [
  { id: 1, campsiteId: 1, author: 'Sarah M.', rating: 5, date: '2026-03-10', text: 'Absolutely stunning views. We could hear the ocean from our site. Will definitely return!' },
  { id: 2, campsiteId: 1, author: 'Jake R.', rating: 5, date: '2026-02-28', text: 'Best campground on the Big Sur coast. Sites are well spaced and the trails are amazing.' },
  { id: 3, campsiteId: 1, author: 'Maria L.', rating: 4, date: '2026-02-15', text: 'Beautiful spot but gets foggy in the mornings. Bring layers.' },
  { id: 4, campsiteId: 3, author: 'Tom K.', rating: 5, date: '2026-03-01', text: 'The hot tub overlooking the lake is perfection. Cabin was immaculate and cozy.' },
  { id: 5, campsiteId: 3, author: 'Emily W.', rating: 5, date: '2026-02-20', text: 'Worth every penny. We came for skiing and the cabin was the perfect home base.' },
  { id: 6, campsiteId: 4, author: 'Chris P.', rating: 5, date: '2026-03-05', text: 'The stargazing here is unreal. Milky Way was crystal clear both nights.' },
  { id: 7, campsiteId: 4, author: 'Nina S.', rating: 4, date: '2026-02-10', text: 'Amazing desert scenery. Bring extra water and sunscreen — no shade at all.' },
  { id: 8, campsiteId: 5, author: 'Dave H.', rating: 5, date: '2026-03-12', text: 'Perfect staging spot for Yosemite. The camp store saved us when we forgot charcoal.' },
  { id: 9, campsiteId: 7, author: 'Olivia B.', rating: 5, date: '2026-03-08', text: 'Most romantic getaway ever. Woke up to ocean sounds and had coffee on our private deck.' },
  { id: 10, campsiteId: 9, author: 'Ryan T.', rating: 5, date: '2026-02-25', text: 'Sleeping in a treehouse surrounded by sequoias is a bucket list experience. 11/10.' },
  { id: 11, campsiteId: 12, author: 'Kai N.', rating: 5, date: '2026-03-15', text: 'The boat ride over sets the mood. Saw dolphins! Snorkeling at the campsite was incredible.' },
  { id: 12, campsiteId: 12, author: 'Priya D.', rating: 4, date: '2026-03-01', text: 'Magical place but be prepared — no fresh water on the island. Pack heavy.' },
  { id: 13, campsiteId: 2, author: 'Greg W.', rating: 4, date: '2026-02-18', text: 'Great RV park. WiFi actually works! Redwood hikes right from the campground.' },
  { id: 14, campsiteId: 6, author: 'Lena F.', rating: 4, date: '2026-03-02', text: 'Cute cabins with a great location. Creek was a bit low but still fun to splash around.' },
  { id: 15, campsiteId: 8, author: 'Marcus J.', rating: 4, date: '2026-01-15', text: 'Hot in summer but the pool is a lifesaver. Great base for exploring the park.' },
  { id: 16, campsiteId: 11, author: 'Amy C.', rating: 5, date: '2026-03-18', text: 'The fireplace cabin with hot tub was incredible after a day of snowshoeing.' },
]
