import { Campsite } from './types'

export const SEED_CAMPSITES: Campsite[] = [
  {
    id: 13,
    name: 'Emerald Cove Tent Camp',
    location: 'Lake Berryessa',
    state: 'CA',
    lat: 38.5488,
    lng: -122.1011,
    type: 'tent',
    rating: 4.4,
    reviewCount: 61,
    pricePerNight: 28,
    available: true,
    amenities: ['Fire pit', 'Picnic table', 'Swimming access', 'Boat launch'],
    description: 'Shaded lakeside sites tucked into oak-studded coves, perfect for morning swims and afternoon kayaking.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: true,
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 14,
    name: 'Pacific Dunes RV Park',
    location: 'Pismo Beach',
    state: 'CA',
    lat: 35.1428,
    lng: -120.6412,
    type: 'rv',
    rating: 4.1,
    reviewCount: 108,
    pricePerNight: 62,
    available: true,
    amenities: ['Full hookups', 'Dump station', 'WiFi', 'Showers', 'Beach access'],
    description: 'Full-hookup RV park steps from the famous Pismo dunes, with direct beach access for ATV rentals and surf sessions.',
    imageUrl: '',
    maxGuests: 8,
    petFriendly: true,
    checkIn: '1:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 15,
    name: 'Whispering Oaks Cabins',
    location: 'Ojai',
    state: 'CA',
    lat: 34.4480,
    lng: -119.2429,
    type: 'cabin',
    rating: 4.7,
    reviewCount: 83,
    pricePerNight: 155,
    available: true,
    amenities: ['Kitchen', 'A/C', 'Fireplace', 'Hammock', 'Hiking trails'],
    description: 'Quiet hillside cabins in Ojai's renowned "pink moment" valley, surrounded by chaparral and citrus groves.',
    imageUrl: '',
    maxGuests: 4,
    petFriendly: false,
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 16,
    name: 'Painted Rock Glamping',
    location: 'San Luis Obispo',
    state: 'CA',
    lat: 35.2828,
    lng: -120.6596,
    type: 'glamping',
    rating: 4.8,
    reviewCount: 39,
    pricePerNight: 195,
    available: false,
    amenities: ['King bed', 'Composting toilet', 'Outdoor shower', 'Vineyard view', 'Wine tasting included'],
    description: 'Bell tents perched above a working vineyard in SLO wine country, with a complimentary tasting at check-in.',
    imageUrl: '',
    maxGuests: 2,
    petFriendly: false,
    checkIn: '4:00 PM',
    checkOut: '10:00 AM',
  },
  {
    id: 17,
    name: 'Lassen Volcanic Basecamp',
    location: 'Mineral',
    state: 'CA',
    lat: 40.4380,
    lng: -121.5085,
    type: 'tent',
    rating: 4.6,
    reviewCount: 57,
    pricePerNight: 22,
    available: true,
    amenities: ['Fire pit', 'Bear locker', 'Vault toilet', 'Thermal pool access'],
    description: 'No-frills tent camp at the edge of Lassen Volcanic National Park, a short trail from boiling mud pots and steaming fumaroles.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: false,
    checkIn: '12:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 18,
    name: 'Sycamore Grove RV Resort',
    location: 'Livermore',
    state: 'CA',
    lat: 37.6819,
    lng: -121.7680,
    type: 'rv',
    rating: 3.8,
    reviewCount: 72,
    pricePerNight: 48,
    available: true,
    amenities: ['Full hookups', 'Pool', 'WiFi', 'Playground', 'Laundry'],
    description: 'Family-friendly RV resort in the Livermore wine valley, close to outlet shopping, golf, and a dozen local wineries.',
    imageUrl: '',
    maxGuests: 8,
    petFriendly: true,
    checkIn: '1:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 19,
    name: 'Owl Creek Retreat',
    location: 'Idyllwild',
    state: 'CA',
    lat: 33.7436,
    lng: -116.7189,
    type: 'cabin',
    rating: 4.9,
    reviewCount: 116,
    pricePerNight: 178,
    available: true,
    amenities: ['Kitchen', 'Fireplace', 'Hot tub', 'WiFi', 'Rock climbing nearby'],
    description: 'Storybook pine-log cabins in Idyllwild with a private hot tub, steps from Tahquitz Rock and the PCT trailhead.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: true,
    checkIn: '3:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 20,
    name: 'Moonstone Beach Camp',
    location: 'Cambria',
    state: 'CA',
    lat: 35.5641,
    lng: -121.0979,
    type: 'tent',
    rating: 4.3,
    reviewCount: 44,
    pricePerNight: 32,
    available: true,
    amenities: ['Fire ring', 'Picnic table', 'Vault toilet', 'Tidepool access'],
    description: 'Bluff-top tent sites above Moonstone Beach where agates wash ashore at low tide and elephant seals bark from the colony below.',
    imageUrl: '',
    maxGuests: 4,
    petFriendly: true,
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
  },
  {
    id: 21,
    name: 'Gold Rush Glamping',
    location: 'Columbia',
    state: 'CA',
    lat: 38.0355,
    lng: -120.4036,
    type: 'glamping',
    rating: 4.5,
    reviewCount: 29,
    pricePerNight: 165,
    available: true,
    amenities: ['Queen bed', 'Wood stove', 'Solar lanterns', 'Panning sluice', 'Mine tour included'],
    description: 'Canvas wall tents on a restored Gold Rush–era claim in the Sierra foothills, with gold panning and a guided mine tour at dusk.',
    imageUrl: '',
    maxGuests: 2,
    petFriendly: false,
    checkIn: '3:00 PM',
    checkOut: '10:00 AM',
  },
  {
    id: 22,
    name: 'Kings Canyon Wilderness Camp',
    location: 'Grant Grove',
    state: 'CA',
    lat: 36.7452,
    lng: -118.9595,
    type: 'tent',
    rating: 4.7,
    reviewCount: 98,
    pricePerNight: 26,
    available: false,
    amenities: ['Bear locker', 'Vault toilet', 'Picnic table', 'Giant sequoia grove', 'Backcountry access'],
    description: 'Remote tent sites surrounded by giant sequoias in Kings Canyon, with mule-deer sightings and canyon views from the rim trail.',
    imageUrl: '',
    maxGuests: 6,
    petFriendly: false,
    checkIn: '12:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 23,
    name: 'Bodega Bay RV Haven',
    location: 'Bodega Bay',
    state: 'CA',
    lat: 38.3324,
    lng: -123.0494,
    type: 'rv',
    rating: 4.0,
    reviewCount: 55,
    pricePerNight: 58,
    available: true,
    amenities: ['Full hookups', 'Dump station', 'WiFi', 'Crab pot rentals', 'Bay view'],
    description: 'Waterfront RV park on the Sonoma Coast where you can drop crab pots from the dock and watch harbor seals bask at sunset.',
    imageUrl: '',
    maxGuests: 8,
    petFriendly: true,
    checkIn: '1:00 PM',
    checkOut: '12:00 PM',
  },
  {
    id: 24,
    name: 'Santa Cruz Redwood Camp',
    location: 'Felton',
    state: 'CA',
    lat: 37.0511,
    lng: -122.0732,
    type: 'tent',
    rating: 4.5,
    reviewCount: 137,
    pricePerNight: 38,
    available: true,
    amenities: ['Fire pit', 'Restrooms', 'Showers', 'Camp store', 'Narrow-gauge railway stop'],
    description: 'Lush tent sites under old-growth coast redwoods in the San Lorenzo Valley, a short walk from the Roaring Camp steam train.',
    imageUrl: '',
    maxGuests: 8,
    petFriendly: true,
    checkIn: '2:00 PM',
    checkOut: '11:00 AM',
  },
]
